service: abstractplay-gameslib-playground

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  profile: AbstractPlayDev

plugins:
  - serverless-finch

custom:
  client:
    bucketName: gameslib.dev.abstractplay.com
    distributionFolder: ./dist
    indexDocument: playground.html
