/** Declaration file generated by dts-gen */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function minmax(gameState: any, gameRules: any, evaluate: any, plies: any, ...args: any[]): any;

